### ISSUE TITLE
Comment from Khronos on MPEG_texture_video extension

### ISSUE THREAD

**Issue by gurdep** [MPEGGroup/Scene-Description#1]
| Comment | Discussion | 
|--| --|
| width and height should be positive rather than non-negative. | Agreed. However, it was overlooked and schema was not modified to reflect this. It will be corrected with the next amendment to the specification.

**Comment by haudiobe** [comment]
AHG 2022/11/7:

- This issue had already been addressed in the FDIS text for ISO/EC 23090-14.
- thanks
