### ISSUE TITLE
Buffer API clarification and typos

### ISSUE THREAD

**Issue by ibouazizi** [MPEGGroup/Scene-Description#10]
The Buffer API defines an API to concurrently access a circular buffer by a reading and writing process. 
One issue that was identified during the implementation is the need for maintaining frames intact in the buffer for as long as the Presentation Engine would need them. That is once, a frame is read and the read_idx is moved forward, the data of the read frame cannot be simply overwritten by the writing process, as it may still be used by the Presentation Engine. A simple solution to this problem is to rely on read operations to create copies of the data. However, that assumption turns out to be very costly for implementations and copy operations should be minimized. Instead, we propose to add a note to make implementers aware of this issue. Potential solutions could be that the frame preceding the read_idx should remain locked for write operations until the read_idx is incremented again. Instead of blocking the write process while waiting for the locked read frame to be released, the write process may skip over it and write into the following frame.
Finally, a typo and an inconsistency in section 6.3 should be corrected. The type is in the table reference in the headerLength row, which should be to Table 24 instead of 27. The inconsistency is between the Frame interface and the header definition in table 24, where the Frame structure lacks the extra parameters.

**Comment by haudiobe** [comment]
Addressed in Amd.2
