### ISSUE TITLE
Issue with spatial audio attenuation enum names' type case: linearDistance vs linear_distance

### ISSUE THREAD

**Issue by nlsdvl** [MPEGGroup/Scene-Description#13]
I just found that ISO/IEC DIS 23090-14 contains conflicting definitions of the audio attenuation functions enum names: 
      A - in Section 5.4.1.2, table 14 camel case is used, eg: **linearDistance**        
      B - While annex D which defines the attenuation functions uses snake case, eg: **linear_distance**

The [public json schema uses linearDistance](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/MPEG_audio_spatial/schema/MPEG_audio_spatial.source.schema.json#L37)

**Comment by haudiobe** [comment]
AHG 2023/10/02 - clearly editorial. Update any linear_distance with linearDistance. DAM2 may already address this.

**Comment by haudiobe** [comment]
Addressed in Amd.2 - thanks
