### ISSUE TITLE
Comment from Khronos on MPEG_scene_dynamic extension

### ISSUE THREAD

**Issue by gurdep** [MPEGGroup/Scene-Description#2]
| Comment | Discussion | 
| -- | -- | 
|The overview section is missing. There is no description of what the extension does or where its object may be located. | A general section has been added in ISO/IEC 23090-14 but it is not included in README.md of the extension. It will be corrected with the next amendment to the specification.

**Comment by haudiobe** [comment]
AHG 2022/11/7:

- This issue had already been addressed in the FDIS text for ISO/EC 23090-14.
- thanks
