### ISSUE TITLE
Incorporate the Khronos suggested editorial fixes to the schemas for the first edition of ISO/IEC 23090-14 

### ISSUE THREAD

**Issue by gurdep** [MPEGGroup/Scene-Description#3]
Thanks to @haudiobe, a pull request (PR) to Khronos glTF repository was submitted. The details of the PR can be found in [Registration of MPEG Extensions for first edition of ISO/IEC 23090-14](https://github.com/KhronosGroup/glTF/pull/2203). 

Khronos reviewed the PR and suggested some editorial fixes to the schemas which were part of the PR. The suggested fixes were implemented by @ibouazizi against the PR. 

In order to stay consistent and adopt the suggested editorial styling, **MPEG scene description AhG** should also implement and incorporate the editorial fixes to the schemas _(provided in the PR)_ as implemented in the Khronos PR.

**Comment by haudiobe** [comment]
Included in the version sent for FDIS ballot.
