### ISSUE TITLE
Missing audio sample rate

### ISSUE THREAD

**Issue by ibouazizi** [MPEGGroup/Scene-Description#5]
The MPEG_audio_spatial.source object, as defined in Table 14 of ISO/IEC 23090-14, lacks an indication of the sample rate of the audio source. This sample rate is required to determine the number of samples to pass per audio frame in the circular buffer. The sample rate is typically equal to the sample rate of the source; but it may differ from it, in which case the media pipeline must perform resampling to get the target sample rate.
In the absence of this information, the Presentation Engine would not know what it is getting and how to setup the audio renderer for that source. The media pipeline might only discover that after selecting and starting the consumption of the media source.

**Comment by ibouazizi** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:////Users/imedbouazizi/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<link rel=themeData
href="file:////Users/imedbouazizi/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:////Users/imedbouazizi/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>


<p class=MsoNormal><span lang=EN-GB style='mso-ansi-language:EN-GB'>We propose
to add a targetSampleRate attribute to the audio source to resolve this issue
as follows:<o:p></o:p></span></p>



Name | Type | Default | Usage | Description
-- | -- | -- | -- | --
id | integer |   | M | unique identifier of the audio source in the scene.
type | string |   | M | Indicates the type of the audio source.    type value equal to “Object” indicates mono object   type value equal to “HOA” indicates HOA object
targetSampleRate | number |   | M | Provides the target audio sampling rate that is   expected to be supplied by the media pipeline of the corresponding audio   source.   If the sampling rate of one of the selected media   source alternatives differs from this   value, then the media pipeline shall perform resampling to match   the target sample rate.
pregain | number | 0.0 | O | provides a level-adjustment in dB for the signal   associated with the source.
playbackSpeed | number | 1.0 | O | defines the playback speed of the audio signal. A value of   1.0 corresponds to playback at normal speed. The value shall be between 0.5   and 2.0.
attenuation | enumeration | “linearDistance” | O | indicates the function used to calculate the attenuation   of the audio signal based on the distance to the source.    attenuation value equal to "“noAttenuation"   indicates no attenuation function should be used.    attenuation value equal to "inverseDistance"   indicates inverse distance function should be used.    attenuation value equal to "linearDistance"   indicates linear distance function should be used.    attenuation value equal to "exponentialDistance"   indicates exponential distance function should be used.    attenuation value equal to "custom" indicates   custom function should be used. The definition of custom function is outside of the scope of this   document.   The attenuation functions and their parameters are specified   in Annex D.
attenuationParameters | array | N/A | O | array of parameters that are input to the attenuation   function. The semantics of these parameters depend on the attenuation   function itself.
referenceDistance | number | 1.0 | O | provides the distance in meters for which the distance   gain is implicitly included in the source signal after application of   pregain.   When type equals ‘HOA’ the element shall not be present.
accessors | array | N/A | M | provides an array of accessor references, by specifying   the accessors indices in accessors array, that describe the buffers where the   decoded audio will be made available.
reverbFeed | array | N/A | O | provides one or more pointers to reverb units, optionally   extended by a floating point scaling factor.   A reverb unit represents a reverberation audio processor   that is configured by the metadata from a single reverb object. Typically, a   reverb object represents reverberation properties of a single room.
reverbFeedGain | array | N/A | O | provides an array of gain [dB] values to be applied to the   source’s signal(s) when feeding it to the corresponding reverbFeed.   The array shall have the same  number of elements as the reverbFeed array   field.




</body>

</html>

**Comment by haudiobe** [comment]
Addressed in Amd.2
