### ISSUE TITLE
Missing Information in MAF API

### ISSUE THREAD

**Issue by ibouazizi** [MPEGGroup/Scene-Description#7]
The Presentation Engine sets up a media pipeline using the MAF API and provides information about the media source and the buffers in which the data is expected. 
The description of the buffer takes a type of BufferInfo, which has the following syntax:
interface BufferInfo {
	attribute integer bufferId;
	attribute BufferHandle handle;
	attribute unsigned long componentType;
	attribute SampleType type;
	attribute integer offset;
	attribute integer stride;
	attribute AttributeType attributeType;
};
Unfortunately, this description lacks information about whether the data is normalized or not. This information would be derived from the accessor.normalized attribute. It would be required to match the expectations of the Presentation Engine in the buffer. The issue may simply be resolved by adding the normailized field to the BufferInfo as follows:
interface BufferInfo {
	attribute integer bufferId;
	attribute BufferHandle handle;
	attribute unsigned long componentType;
     attribute boolean normalized;
	attribute SampleType type;
	attribute integer offset;
	attribute integer stride;
	attribute AttributeType attributeType;
};

**Comment by haudiobe** [comment]
Addressed in Amd.2
