### ISSUE TITLE
Missing AttributeType

### ISSUE THREAD

**Issue by ibouazizi** [MPEGGroup/Scene-Description#9]
This leads to another issue, related to the the AttributeType. Currently, the following AttributeTypes are defined in the spec:
enum AttributeType {"ATTRIB_NORMAL","ATTRIB_POSITION","ATTRIB_COLOR", "ATTRIB_TEXCOORD","ATTRIB_INDEX","ATTRIB_TANGENT", "ATTRIB_WEIGHTS", "ATTRIB_JOINTS"}
These do not support the indication that the data is an audio attribute of an object. So, we suggest that a new attribute type is defined: ATTRIB_AUDIO.

**Comment by haudiobe** [comment]
Addressed in Amd.2. Added PCM and metadata
